#%RAML 1.0
title: Customers API


types:
  customers: !include data-types/custDataType.raml

/customers:
  description: Fetch all the customers
  get:
    responses:
      200:
        body:
          application/json:
            type: customers[]
  
  /{customerId}:
    description: Fetch single customers
    get:
      responses:
        200:
          body:
            application/json:
              type: customers
            