#%RAML 1.0 Trait

responses:
  400:
    body:
      application/json:
        example: !include ../examples/errorResp.json
  404:
    body:
      application/json:
        example: !include ../examples/errorResp.json
  401:
    body:
      application/json:
        example: !include ../examples/errorResp.json
  500:
    body:
      application/json:
        example: !include ../examples/errorResp.json
