#%RAML 1.0 DataType

type:
  properties:
    accountId:
      type: string
      example: "123"
    
    accountType: 
      type: string
      example: "Savings"
    
    customerId:
      type: string
      example: "1"