#%RAML 1.0 DataType


type: 
  properties:
    id:
      type: string
      example: "334344324"
    firstName:
      type: string
      example: "Jitendra"
    lastName:
      type: string
      example: "Bafna"
    address:
      type: string
      example: "Oxford Road"
    phone:
      type: string
      example: "343434343"
    website:
      type: string
      example: "www.xyz.com"
    company:
      type: string
      example: "Self"
    accountType:
      type: string
      example: "Saving"
      