#%RAML 1.0 DataType

type: 
  properties:
    balanceType:
      type: string
      example: "Credit Limit"
    amount:
      type: string
      example: "43434.56"
    accountId:
      type: string
      example: "1"