#%RAML 1.0 DataType

type: 
  properties:
    transactionId:
      type: string
      example: "21213321"
    description:
      type: string
      example: "Credit Card Payment"
    amount:
      type: string
      example: "434.45"
    currency:
      type: string
      example: "INR"
    transactionDate:
      type: string
      example: "2021-06-15"
    accountId:
      type: string
      example: "1"